Description of demo_ge_poly
Home > hmm_smast > dependencies > googleearthtoolbox > matlab > demo > demo_ge_poly.m
demo_ge_poly
PURPOSE
SYNOPSIS
function demo_ge_poly()%% Demo ge_poly
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ge_output Reference page in help browser:
ge_poly Reference page in help browser:
googleearthroot
This function is called by:
SOURCE CODE
function demo_ge_poly()%% Demo ge_poly
load(fullfile(googleearthroot,'data','conus.mat'));
world_coasts = ge_poly(uslon,uslat,...
                       'polyColor','9933ffff',...
                        'altitude',150000,...
                    'altitudeMode','relativeToGround',...
                         'extrude',1,...
                      'tessellate',true);
kmlFileName = 'demo_ge_poly.kml';
ge_output(kmlFileName,world_coasts);