Description of demo_ge_makekmz
Home > hmm_smast > dependencies > googleearthtoolbox > matlab > demo > demo_ge_makekmz.m
demo_ge_makekmz
PURPOSE
specify directory to store collada models:
SYNOPSIS
function demo_ge_makekmz()
DESCRIPTION
 specify directory to store collada models:
CROSS-REFERENCE INFORMATION
This function calls:
ge_barbdaes Reference page in help browser:
ge_makekmz
ge_output Reference page in help browser:
ge_windbarb % Reference page in help browser:
googleearthroot
This function is called by:
SOURCE CODE
function demo_ge_makekmz()
% specify directory to store collada models:
rLinkStr = ['barbs',filesep];
% generate lime-colored collada models:
ge_barbdaes('daeDir',rLinkStr,...
            'barbColor','FFFF00',...
            'barbAlpha','A0',...
            'msgToScreen',false)
kmlStr = ge_windbarb(10,20,300,10,0,...
    'arrowScale',1e5,...
    'rLink',rLinkStr);
ge_output('barbs.kml',kmlStr)
sources = {fullfile(googleearthroot,'data','barbdaes');
            'barbs.kml'};
destinations = {rLinkStr;
                   'barbs.kml'};
ge_makekmz('barbs.kmz','sources',sources,...
                  'destinations',destinations)