Description of deglong
Home > backfun > deglong.m
deglong
PURPOSE
DEGLONG returns the length (in km) of one degree of longitude at the latitude
SYNOPSIS
function longfac = deglong(lat)
DESCRIPTION
DEGLONG returns the length (in km) of one degree of longitude at the latitude
        given as input to the function.
   This function is called by readdb.m, samptrack.m and mptrack.m
   This function should not be called manually by the user.
   Date: 12/12 - 2007, ver. 0.51
   HMM geolocation toolbox, IMM and DIFRES
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mptrack MPTRACK Find the Most Probable Track.
samptrack SAMPTRACK Sample random tracks from a geolocation result.
gen_tidaldb_draft lonmin=-71;lonmax=-66;latmin=39;latmax=44;delta=.1;
readdb READDB Read the plain database text files and store in a .mat file.
SOURCE CODE
function longfac = deglong(lat)
%DEGLONG returns the length (in km) of one degree of longitude at the latitude
%        given as input to the function.
%
%   This function is called by readdb.m, samptrack.m and mptrack.m
%
%   This function should not be called manually by the user.
%
%   Date: 12/12 - 2007, ver. 0.51
%   HMM geolocation toolbox, IMM and DIFRES
lat = lat*pi/180;
a = 6378.137;
b = 6356.7523;
longfac = pi/180*cos(lat).*sqrt((a^4*cos(lat).^2 + b^4*sin(lat).^2)./(a^2*cos(lat).^2 + b^2*sin(lat).^2));