Description of normalise
Home > backfun > normalise.m
normalise
PURPOSE
NORMALISE Normalises a distribution to sum to 1.
SYNOPSIS
function [pdf,normConst]=normalise(pdf)
DESCRIPTION
NORMALISE Normalises a distribution to sum to 1.
   This function is omnipresent throughout the toolbox.
   This function should not be called manually by the user.
   Date: 24/7 - 2007, ver. 0.5
   HMM geolocation toolbox, IMM and DIFRES
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plottingbw PLOTTINGBW Plot the result of a geolocation.
hmmfilter HMMFILTER Perform the forward sweep of the filtering.
hmmgeolocate1 HMMGEOLOCATE Obtain geolocation by filtering preprocessed data
smoothing SMOOTHING Perform the backward sweep of the filtering.
plotud PLOTUD Plot a utilisation distribution.
pplotdistr PPLOTDISTR Plot a distribution to be used in a paper.
pplotlik function pplotlik(LIK,result,typ,day,lonrange,latrange)
proboftrack PROBOFTRACK Calculate the probability of a track given the observations.
samptrack SAMPTRACK Sample random tracks from a geolocation result.
SOURCE CODE
function [pdf,normConst]=normalise(pdf)
%NORMALISE Normalises a distribution to sum to 1.
%
%   This function is omnipresent throughout the toolbox.
%
%   This function should not be called manually by the user.
%
%   Date: 24/7 - 2007, ver. 0.5
%   HMM geolocation toolbox, IMM and DIFRES
normConst = sum(pdf(:));%+eps^20;
pdf = pdf/normConst;