Description of ex003_test
Home > dependencies > googleearthtoolbox > matlab > doc > ex003_test.m
ex003_test
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ge_output Reference page in help browser:
ge_plot3 Reference page in help browser:
rad2deg
This function is called by:
SOURCE CODE
clear
close all
clc
Amp = 5e6;
a = linspace(-pi,pi,61)';
X = rad2deg(a);
Y = zeros(size(a));
Z = abs(sin(a*2)*Amp);
x=[];
y=[];
z=[];
for f=1:2:length(X)-1
    x=[x;X(f:f+1);NaN];
    y=[y;Y(f:f+1);NaN];
    z=[z;Z(f:f+1);NaN];
end
kmlStr = ge_plot3(X,Y,Z,'forceAsLine',true,'extrude',1);
p=mfilename('fullpath');
[ppath,pname,pext,pvrsn]=fileparts(p);
ge_output(['..',filesep,'kml',filesep,pname,'.kml'],kmlStr,'name',pname);