Description of deg2rad
Home > dependencies > googleearthtoolbox > matlab > deg2rad.m
deg2rad
PURPOSE
SYNOPSIS
function [angle_rad]=deg2rad(angle_deg)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_ge_quiver3_2 Define the location of the Collada model origin:
ge_axes Reference page in help browser:
ge_circle Reference page in help browser:
ge_cylinder Reference page in help browser:
test_dyn_vis
test_ge_quiver3 Define the location of the Collada model origin:
SOURCE CODE
function [angle_rad]=deg2rad(angle_deg)
angle_rad=(angle_deg*2*pi)/360;