Description of ge_folder
Home > hmm_smast > dependencies > googleearthtoolbox > matlab > ge_folder.m
ge_folder
PURPOSE
Reference page in help browser:
SYNOPSIS
function foutput = ge_folder(foldername,output,varargin)
DESCRIPTION
 Reference page in help browser:
 <a href="matlab:web(fullfile(ge_root,'html','ge_folder.html'),'-helpbrowser')">link</a> to html documentation
 <a href="matlab:web(fullfile(ge_root,'html','license.html'),'-helpbrowser')">show license statement</a>
CROSS-REFERENCE INFORMATION
This function calls:
authoptions % all available options to each function
parsepairs % Please use the link below to view the documentation.
This function is called by:
demo_ge_folder
demo_ge_point Example usage of the ge_point function.
demo_ge_point_new Example usage of the ge_point function.
demo_ge_quiver3_1
demo_ge_quiver3_2 Define the location of the Collada model origin:
demo_ge_screenoverlay
ge_axes Reference page in help browser:
ge_windbarb % Reference page in help browser:
test_dyn_vis
test_ge_quiver3 Define the location of the Collada model origin:
SOURCE CODE
function foutput = ge_folder(foldername,output,varargin)
% Reference page in help browser:
%
% <a href="matlab:web(fullfile(ge_root,'html','ge_folder.html'),'-helpbrowser')">link</a> to html documentation
% <a href="matlab:web(fullfile(ge_root,'html','license.html'),'-helpbrowser')">show license statement</a>
%
AuthorizedOptions = authoptions(mfilename);
    snippet = ' ';
description = '';
 visibility = 1;
parsepairs %script that parses Parameter/value pairs.
if snippet==' '
    snippet_chars = '';
else
     snippet_chars = [ '<Snippet>' snippet '</Snippet>',10 ];
end
description_chars = [ '<description>',10,'<![CDATA[' description ']]>',10,'</description>',10 ];
visibility_chars = [ '<visibility>',10,int2str(visibility),10,'</visibility>',10];
header = [ '<Folder id="' foldername '">',...
           '<name>',foldername,'</name>',...
           visibility_chars,10,...
           snippet_chars,10,...
           description_chars,10 ];
footer = '</Folder>';
foutput = [header output footer];