Description of ge_output
Home > hmm_smast > dependencies > googleearthtoolbox > matlab > ge_output.m
ge_output
PURPOSE
Reference page in help browser:
SYNOPSIS
function ge_output(filename,output,varargin)
DESCRIPTION
 Reference page in help browser:
 <a href="matlab:web(fullfile(ge_root,'html','ge_output.html'),'-helpbrowser')">link</a> to html documentation
 <a href="matlab:web(fullfile(ge_root,'html','license.html'),'-helpbrowser')">show license statement</a>
CROSS-REFERENCE INFORMATION
This function calls:
authoptions % all available options to each function
parsepairs % Please use the link below to view the documentation.
This function is called by:
demo_ge_axes
demo_ge_box % Demo ge_box
demo_ge_circle
demo_ge_colorbar
demo_ge_contour
demo_ge_contourf
demo_ge_cylinder
demo_ge_folder
demo_ge_gplot
demo_ge_grid % Demo ge_grid
demo_ge_groundoverlay
demo_ge_imagesc
demo_ge_imagesc_old Demo ge_imagesc_old
demo_ge_makekmz specify directory to store collada models:
demo_ge_output % Demo ge_output
demo_ge_plot
demo_ge_plot3
demo_ge_point Example usage of the ge_point function.
demo_ge_point_new Example usage of the ge_point function.
demo_ge_poly
demo_ge_poly3
demo_ge_quiver3_1
demo_ge_quiver3_2 Define the location of the Collada model origin:
demo_ge_scatter
demo_ge_screenoverlay
demo_ge_surf
demo_ge_surf_mesh
demo_ge_text
demo_ge_windbarb2
ex002_test
ex003_test
example_ge_poly
test_dyn_vis
test_ge_gplot
test_ge_quiver3 Define the location of the Collada model origin:
test_id_links
write_ge_track write the most probably track to a google earth file
write_ge_track_UD write the most probably track to a google earth file
SOURCE CODE
function ge_output(filename,output,varargin)
% Reference page in help browser:
%
% <a href="matlab:web(fullfile(ge_root,'html','ge_output.html'),'-helpbrowser')">link</a> to html documentation
% <a href="matlab:web(fullfile(ge_root,'html','license.html'),'-helpbrowser')">show license statement</a>
%
AuthorizedOptions = authoptions(mfilename);
% Assign default values to parameters:
       name = filename;
msgToScreen = false;
parsepairs %script that parses Parameter/value pairs.
if msgToScreen
   disp(['Running ' mfilename '...'])
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fileoutput = filename((end-2):end);
if strcmp(fileoutput,'kml')
    fid = fopen(filename, 'wt');
    header = ['<?xml version="1.0" encoding="UTF-8"?>',10,...
             '<kml xmlns="http://earth.google.com/kml/2.1">',10,...
             '<Document>',10,...
             '<name>',10,name,10,'</name>',10];
    footer = [10,'</Document>',10,...
        '</kml>'];
    fprintf(fid,'%s',header);
    fprintf(fid,'%s',output);
    fprintf(fid,'%s',footer);
    fclose(fid);
elseif strcmp(fileoutput,'kmz')
    newfilename = filename(1:(end-4));
    newfilename = strcat(newfilename,'.kml');
    fid = fopen( newfilename, 'wt');
    header = ['<?xml version="1.0" encoding="UTF-8"?>',10,...
             '<kml xmlns="http://earth.google.com/kml/2.1">',10,...
             '<Document>',10,...
             '<name>',10,name,10,'</name>',10];
    footer = [10,'</Document>',10,...
        '</kml>',10];
    fprintf(fid,'%s',header);
    fprintf(fid,'%s',output);
    fprintf(fid,'%s',footer);
    fclose(fid);
    zip(filename,newfilename);
    if ispc
        system(['del ',newfilename] );
        system(['move ',filename, '.zip ', filename]);
    else
        system(['rm -f ',newfilename]);
        system(['mv ',filename, '.zip ', filename]);
    end
else
    error('unsupported file extension used in ge_output');
end
if msgToScreen
   disp(['Running ' mfilename '...Done'])
end