Description of googleearthroot
Home > hmm_smast > dependencies > googleearthtoolbox > matlab > googleearthroot.m
googleearthroot
PURPOSE
SYNOPSIS
function s=googleearthroot()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_all % Demonstrate All functions
demo_ge_groundoverlay
demo_ge_imagesc
demo_ge_makekmz specify directory to store collada models:
demo_ge_poly
demo_ge_quiver3_1
demo_ge_quiver3_2 Define the location of the Collada model origin:
googleearth
openInBrowser
SOURCE CODE
function s=googleearthroot()
a=mfilename('fullpath');
Ix=findstr(a,filesep);
s=a(1:Ix(end));