Description of parsepairs
Home > hmm_smast > dependencies > googleearthtoolbox > matlab > parsepairs.m
parsepairs
PURPOSE
% Please use the link below to view the documentation.
SYNOPSIS
This is a script file.
DESCRIPTION
 % Please use the link below to view the documentation.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ge_axes Reference page in help browser:
ge_barbdaes Reference page in help browser:
ge_box Reference page in help browser:
ge_circle Reference page in help browser:
ge_colorbar Reference page in help browser:
ge_contour Reference page in help browser:
ge_contour_old Reference page in help browser:
ge_contour_old2 Reference page in help browser:
ge_contourf Reference page in help browser:
ge_contourf_old Reference page in help browser:
ge_contourf_old2 Reference page in help browser:
ge_cylinder Reference page in help browser:
ge_folder Reference page in help browser:
ge_gplot Reference page in help browser:
ge_grid Reference page in help browser:
ge_groundoverlay Reference page in help browser:
ge_imagesc Reference page in help browser:
ge_imagesc_TMP Reference page in help browser:
ge_imagesc_old Reference page in help browser:
ge_kml Reference page in help browser:
ge_kmz Reference page in help browser:
ge_makekmz
ge_output Reference page in help browser:
ge_plot Reference page in help browser:
ge_plot3 Reference page in help browser:
ge_point Reference page in help browser:
ge_point_new Reference page in help browser:
ge_poly Reference page in help browser:
ge_poly3 Reference page in help browser:
ge_polyplace Reference page in help browser:
ge_quiver3 Reference page in help browser:
ge_region
ge_scatter
ge_screenoverlay Reference page in help browser:
ge_surf
ge_windbarb % Reference page in help browser:
ge_writecollada Reference page in help browser:
old_ge_barbdaes
SOURCE CODE
%
% % Please use the link below to view the documentation.
% % If you don't see the link which is automatically inserted by MATLAB,
% % try removing the line break above, so that this help block is merged
% % with the previous one.
% % Reference page in help browser: <a href="matlab:doc parsepairs">parsepairs</a>
for k = 1:2:length(varargin(:))
    if ~strcmp(varargin{k}, AuthorizedOptions)
        s=dbstack;
        error(['Unauthorized parameter name ' 39 varargin{k} 39 ' in ' 10,...
            'parameter/value passed to ' 39 s(end-1).name 39 '.']);
    end
    eval([varargin{k},'=varargin{',num2str(k+1),'};'])
end
if ~isempty(varargin)
    clear k
end