Description of write_ge_track_UD
Home > postprocessing > write_ge_track_UD.m
write_ge_track_UD
PURPOSE
write the most probably track to a google earth file
SYNOPSIS
function write_ge_track_UD(tagno)
DESCRIPTION
 write the most probably track to a google earth file
CROSS-REFERENCE INFORMATION
This function calls:
ge_colorbar Reference page in help browser:
ge_imagesc Reference page in help browser:
ge_output Reference page in help browser:
ge_plot Reference page in help browser:
ge_point Reference page in help browser:
This function is called by:
run_tag clear all;
run_tag clear all;
SOURCE CODE
% write the most probably track to a google earth file
function write_ge_track_UD(tagno)
%WRITE_GE_TRACK : dump a track (lon,lat,time) to a google earth file
%   HANDLE = WRITE_GE_TRACK(TRACK)
%
%   - TRACK a struct containing an output from eg. samptrack.
%
%     Optional arguments
%
%  EXAMPLE
%   WRITE_GE_TRACK(mpt)
%
%   Date: 3/16/12
%   G. Cowles
%   Date: 11/13/14
%   C. Liu
% load files
filename = sprintf('mpt%s',tagno);
load(filename);
filename = sprintf('result%s',tagno);
load(filename);
load tidaldb
% transfer data
time = mpt.time;
drels = time(1);
drcap = time(end);
lon = mpt.long;
lat = mpt.lat;
catch_long=mpt.catch_long;
catch_lat=mpt.catch_lat;
kmlFileName = [mpt.tagno '.kml'];
rls_iconStr = 'http://maps.google.com/mapfiles/kml/pal3/icon38.png';
rcp_iconStr = 'http://maps.google.com/mapfiles/kml/pal5/icon13.png';
rcprp_iconStr = 'http://maps.google.com/mapfiles/kml/pal5/icon14.png';
dot_iconStr = 'http://maps.google.com/mapfiles/kml/pal4/icon49.png';
dstr = datestr(time(1), 'yyyy-mm-ddTHH:MM:SSZ');
dstr2 = datestr(time(end), 'yyyy-mm-ddTHH:MM:SSZ');
% dump release/recap/icons
kmlstr  = '';
kmlstr = [kmlstr,ge_point(lon(1),lat(1),0., ...
                     'iconURL',rls_iconStr,...
                     'msgToScreen',true,...
                     'pointDataCell',{'Lon',num2str(lon(1),'%5.2f');...
                                      'Lat',num2str(lat(1),'%5.2f');...
                                      'Release Date',datestr(drels);,...
                                      'Recap Date'  ,datestr(drcap);,...
                                      'Days at Liberty',int2str(ceil(drcap-drels))},...
                     'timeSpanStart', char(dstr), ...
                     'timeSpanStop',  char(dstr2 ), ...
                     'name',[mpt.tagno])];
kmlstr = [kmlstr,ge_point(lon(end),lat(end),0., ...
                     'iconURL',rcp_iconStr,...
                     'msgToScreen',true,...
                     'pointDataCell',{'Lon',num2str(lon(end),'%5.2f');...
                                      'Lat',num2str(lat(end),'%5.2f');...
                                      'Release Date',datestr(drels);,...
                                      'Recap Date'  ,datestr(drcap);,...
                                      'Days at Liberty',int2str(ceil(drcap-drels))},...
                     'timeSpanStart', char(dstr), ...
                     'timeSpanStop',  char(dstr2 ), ...
                     'name',[mpt.tagno])];
kmlstr = [kmlstr,ge_point(catch_long,catch_lat,0., ...
                     'iconURL',rcprp_iconStr,...
                     'msgToScreen',true,...
                     'pointDataCell',{'Lon',num2str(catch_long,'%5.2f');...
                                      'Lat',num2str(catch_lat,'%5.2f');...
                                      'Release Date',datestr(drels);,...
                                      'Recap Date'  ,datestr(drcap);,...
                                      'Days at Liberty',int2str(ceil(drcap-drels))},...
                     'timeSpanStart', char(dstr), ...
                     'timeSpanStop',  char(dstr2 ), ...
                     'name',[mpt.tagno])];
kmlstr  =  [kmlstr, ge_plot(lon,lat,...
                     'altitude',100,...
                     'forceAsLine',false,...
                     'tessellate',true,...
                     'lineWidth',2,...
                     'timeSpanStart', char(dstr), ...
                     'timeSpanStop',  char(dstr2 ), ...
                     'altitudeMode','clampToGround')];
for i=1:numel(time)-1
  dstr = datestr( time(i), 'yyyy-mm-ddTHH:MM:SSZ')
  dstr2 = datestr( time(i+1), 'yyyy-mm-ddTHH:MM:SSZ')
  kmlstr = [kmlstr,ge_point(lon(i),lat(i),0., ...
                       'iconURL',dot_iconStr,...
                       'msgToScreen',true,...
                       'timeSpanStart', char(dstr), ...
                       'timeSpanStop', char(dstr2))];
end;
% plot UD
load cmapfancy
data = result.UD;
x = db.long(1,:);
y = flipud(db.lat(:,1));
cLimLow = min(min(data));
cLimHigh = max(max(data));
altitude = 0;
alphaMatrix = ones(size(data))*0.75;
output = ge_imagesc(x,y,data,...
                    'imgURL',['UD_' mpt.tagno '.png'],...
                   'cLimLow',cLimLow,...
                  'cLimHigh',cLimHigh,...
                  'altitude',altitude,...
              'altitudeMode','absolute',...
               'alphaMatrix',alphaMatrix,...
               'colorMap',cmapfancy);
output2 = ge_colorbar(x(end),y(1),data,...
                          'numClasses',20,...
                             'cLimLow',cLimLow,...
                            'cLimHigh',cLimHigh,...
                       'cBarFormatStr','%+07.4f',...
                            'colorMap',cmapfancy);
kmlstr = [output2 output kmlstr];
kmlTargetDir = [''];%..',filesep,'kml',filesep];
ge_output([kmlTargetDir,kmlFileName],[kmlstr],'name',kmlFileName);
%endf = ge_folder('endpoints', endstr);
%trackf = ge_folder('track', kmlstr);
%ge_output(kmlFileName,[endf]);